### ISSUE TITLE
Accessing main webclient UI variables/functions from inside a modern plugin

### ISSUE THREAD

**Issue by kvb2univpitt** [hms-dbmi/i2b2v2-webclient#38]
In the current version of the webclient, I am able to get the certain user info via the following:

```js
i2b2.PM.model.isAdmin; \\ determine if the user is an admin
i2b2.h.getDomain();  \\ get the i2b2 domain
i2b2.h.getProject() \\ get the i2b2 project
i2b2.h.getPass(); \\ get the i2b2 user session ID
```

How do I retrieve all of the information above in the new plugin structure?

Thanks,
Kevin

**Comment by hackerceo** [comment]
If you use the standard i2b2 AJAX calls from the plugin environment you do
not need to specify those items in the transport to send the messages to
the hive.  It is handled automatically.

At this time, we have not exposed to the new plugins a way to get the
user's security credentials.  This is an attempt to harden the client's
security design.

Can you share the use case for having a plugin access this information?

Best Regards,
Nick Benik

**Comment by kvb2univpitt** [comment]
Hi Nick,

This is for our i2b2 [ontology-store plugin](https://github.com/kvb2univpitt/ontology-store).  I am working on porting this plugin over to the new plugin structure: [https://github.com/kvb2univpitt/ontology-store/tree/i2b2v2-webclient](https://github.com/kvb2univpitt/ontology-store/tree/i2b2v2-webclient).

The plugin allows users to download ontology onto their servers and install them with just a click of a button.  The way it works is that the user has to have admin privileges.  This is where the ***i2b2.PM.model.isAdmin*** comes in.  The values for i2b2.h.getDomain(), i2b2.h.getProject(), and i2b2.h.getPass() are then passed to the ontology server to verify the user is a valid user and that the current session is a valid session before downloading the ontology and install it.

What's the best way to do this in the new plugin structure?

Thanks,
Kevin

**Comment by hackerceo** [comment]
Given the needs of your plugin I think it will be necessary for us to make
a configuration option to expose this functionality for your plugin.  Lets
take this offline to do proper requirements gathering and perhaps have a
call about it.  I'll email you a little later this week once I talk to the
rest of the team.

**Comment by kvb2univpitt** [comment]
@hackerceo Hi Nick.  I just want to touch base to see if we are meeting up to talk about adding function to access logged-in user info in the new webclient.  Thanks, Kevin

**Comment by hackerceo** [comment]
Very big apologies! This dropped off my radar! Let me try to get it put
into this sprint and get some resources behind it.

Best Regards,
Nick Benik

**Comment by kvb2univpitt** [comment]
@hackerceo Thank you.  I also need help on how to access the function ***i2b2.ONT.view.nav.doRefreshAll*** from the plugin.  The function is there in the file [ONT_view_Nav.js](https://github.com/hms-dbmi/i2b2v2-webclient/blob/master/js-i2b2/cells/ONT/ONT_view_Nav.js).  It doesn't seem like the plugin can access that function directly.

**Comment by hackerceo** [comment]
@kvb2univpitt, we have designed an additional system for the new modern plugins to use called **AuthorizedTunnel** that will allow modern plugins to have controlled access to functions and variables that are internal to the main i2b2 webclient from within their isolated iframe.

To authorize access to internal functions/variables you must define them in your `plugin.json` file under a section named "**authorizedTunnel**".  The next level consists of an object named "**variables**" and an array called "**functions**".  

For the `authorizedTunnel.variables` object, its key-value pair is the full access path (from the global namespace) as its key and a string representing the access permissions to that variable.  The valid variables are: "**R**" for read access,  "**W**" for write access, and "**O**" for object access which allows retrieval or setting of a complex object at that variable access location.  If the "**O**" option is not set then normal variable operations can only occur with the following data types: _string_, _number_ and _boolean_.

For the `authorizedTunnel.functions` array, it contains a list of strings that specify the full access path (from the global namespace) used to make the the function call.

When defining the full access path for variables and functions the only valid namespace navigator is the period ("**.**") such as in `i2b2.ONT.view.nav.doRefreshAll` whereas the following navigation method will fail `i2b2['ONT'].view['nav'].doRefreshAll`

To get access to the functionality you need in the main i2b2 webclient you should add the following code into your plugin's configuration file (`plugin.json`) contained in your plugin's root directory:

```json
{
  ...your existing config...

  "authorizedTunnel": {
    "variables" :{
      "i2b2.PM.model.isAdmin": "R"
    },
    "functions": [
      "i2b2.h.getDomain",
      "i2b2.h.getProject",
      "i2b2.h.getUser",
      "i2b2.h.getPass",
      "i2b2.ONT.view.nav.doRefreshAll"
    ]
  }
}
```

**Comment by kvb2univpitt** [comment]
@hackerceo Thank you very much for working on this!  I will give it a try sometime next week.  Thanks again.

**Comment by hackerceo** [comment]
@kvb2univpitt, here is the documentation on how to access a variable using the new AuthorizedTunnel functionality.

To access a variable in the main UI from within your plugin you will use the functionality found at the **i2b2.authorizeTunnel.variable[]** namespace.

Do to the asynchronous nature of the plugin + main UI interactions you will get back a JS Promise when you request the value of a variable from within the main i2b2 UI.

```javascript
// The "result" variable will be a JS Promise that is passed the current value i2b2.PM.model.isAdmin 
// from the main UI window
let result = i2b2.authorizedTunnel.variable["i2b2.PM.model.isAdmin"];

// here is another way to retrieve and then work with the remote variable's value
i2b2.authorizedTunnel.variable["i2b2.PM.model.isAdmin"].then((isActuallyAdmin) => { 
  if (isActuallyAdmin) {
    alert('You are an i2b2 Admin');
  } else {
    alert('You are NOT an i2b2 Admin');
});
```

When you are setting the value of a variable within the main i2b2 UI you do so as shown in the below example. If a problem is encountered (ie, security restrictions) an error will be thrown asynchronously in your plugin code's window.

```javascript
i2b2.authorizedTunnel.variable["i2b2.PM.model.isAdmin"] = true;
```

**Comment by kvb2univpitt** [comment]
@hackerceo Thank you very much!  That is very helpful!  I'll play around with it this evening and will let you know how it goes.  Thanks again.

**Comment by kvb2univpitt** [comment]
@hackerceo Work like a charm!!!

Here's how I use it:

```js
i2b2.OntologyStore = {
    env: {
        isAdmin: false,
        project: '',
        domain: '',
        user: '',
        session: ''
    },
    func: {
        doRefreshAll: function () {
            i2b2.authorizedTunnel.function["i2b2.ONT.view.nav.doRefreshAll"]().then((doRefreshAll) => {
                doRefreshAll();
            });
        }
    }
};

window.addEventListener("I2B2_READY", () => {
    // set the variables for later use
    i2b2.authorizedTunnel.variable["i2b2.PM.model.isAdmin"].then((isAdmin) => {
        i2b2.OntologyStore.env.isAdmin = isAdmin;
    });
    i2b2.authorizedTunnel.function["i2b2.h.getDomain"]().then((domain) => {
        i2b2.OntologyStore.env.domain = domain;
    });
    i2b2.authorizedTunnel.function["i2b2.h.getProject"]().then((project) => {
        i2b2.OntologyStore.env.project = project;
    });
    i2b2.authorizedTunnel.function["i2b2.h.getUser"]().then((user) => {
        i2b2.OntologyStore.env.user = user;
    });
    i2b2.authorizedTunnel.function["i2b2.h.getPass"]().then((session) => {
        i2b2.OntologyStore.env.session = session;
    });
});
```

This way I can just call  i2b2.OntologyStore.env.isAdmin,  i2b2.OntologyStore.env.domain, etc from my code.

Thanks again for all your help!

**Comment by hackerceo** [comment]
@kvb2univpitt, here is the documentation on how to execute an internal UI function using the new AuthorizedTunnel functionality.

To execute a function that exists in the main UI from within your plugin you will use the functionality found at the i2b2.authorizedTunnel.function[] namespace.

Do to the asynchronous nature of the plugin + main UI interactions you will get back a JS Promise when you execute the function from within the main i2b2 UI.

```javascript
i2b2.authorizedTunnel.function["i2b2.myFunction"](my, function, parameters).then((functionResults) => { console.dir(functionResults)})
```

For the code you posted above I believe you can just remove the handling if the returned promise in your code since the **i2b2.ONT.view.nav.doRefreshAll** function does not return any value.  It is also unclear what the calling of the plugin-scoped function **doRefreshAll()** does.

I am glad we were able to figure out a way to allow the new plugins to be able to securely reach into the main UI variables and functions.  Please let open another issue if you find anything else and we look forward to seeing how your newly refactored plugin works using the new i2b2 plugin framework.

**Comment by kvb2univpitt** [comment]
@hackerceo I see what you're saying.  I thought the promise returns a handle to the function.  Instead, it returns the returned value from the function, if any.  Since there's no returned value in this case, I changed my code to this:

```js
i2b2.OntologyStore = {
    func: {
        doRefreshAll: function () {
           i2b2.authorizedTunnel.function["i2b2.ONT.view.nav.doRefreshAll"]();
        }
    }
};
```
I basically invoke the method ```i2b2.OntologyStore.func.doRefreshAll();``` to do a refresh.

Thanks for the feedback!

**Comment by kvb2univpitt** [comment]
@hackerceo If you want to try out the plugin, here's the branch:
https://github.com/kvb2univpitt/ontology-store/tree/i2b2v2-webclient-datatables

Just follow the instruction and you should be good to go.
